// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALTq0WLeFJjXbarsN2oMk4Rn3bryzLZFc',
    appId: '1:303400197676:web:79f5700fb62548dd47bb89',
    messagingSenderId: '303400197676',
    projectId: 'kigali-services-4b600',
    authDomain: 'kigali-services-4b600.firebaseapp.com',
    storageBucket: 'kigali-services-4b600.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAggcqmo9CF0OKV_cdNcivhm5l6KDENw_o',
    appId: '1:303400197676:android:09327b6d6ed00aba47bb89',
    messagingSenderId: '303400197676',
    projectId: 'kigali-services-4b600',
    storageBucket: 'kigali-services-4b600.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWtl11OHoHUZMGERzcjPFaj5Ix5WJ4wL0',
    appId: '1:303400197676:ios:e37d0cce280b52c147bb89',
    messagingSenderId: '303400197676',
    projectId: 'kigali-services-4b600',
    storageBucket: 'kigali-services-4b600.firebasestorage.app',
    iosBundleId: 'com.example.kigaliServices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWtl11OHoHUZMGERzcjPFaj5Ix5WJ4wL0',
    appId: '1:303400197676:ios:e37d0cce280b52c147bb89',
    messagingSenderId: '303400197676',
    projectId: 'kigali-services-4b600',
    storageBucket: 'kigali-services-4b600.firebasestorage.app',
    iosBundleId: 'com.example.kigaliServices',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALTq0WLeFJjXbarsN2oMk4Rn3bryzLZFc',
    appId: '1:303400197676:web:dce1f2dbd027968847bb89',
    messagingSenderId: '303400197676',
    projectId: 'kigali-services-4b600',
    authDomain: 'kigali-services-4b600.firebaseapp.com',
    storageBucket: 'kigali-services-4b600.firebasestorage.app',
  );
}
